package net.axay.blaubot.commands.implementation.anime

import com.gitlab.kordlib.kordx.emoji.Emojis
import dev.kord.common.annotation.KordPreview
import dev.kord.core.behavior.followUp
import dev.kord.core.entity.interaction.Interaction
import net.axay.blaubot.commands.api.SlashCommand

private val animeList = listOf(
    "Steins;Gate",
    "Overlord",
    "Akame ga Kill!",
    "Devilman Crybaby",
    "The Promised Neverland",
    "Gurren Lagann",
    "Food Wars! Shokugeki no Soma",
    "Kuroko's Basketball",
    "Seven Deadly Sins",
    "Mob Psycho 100",
    "Assassination Classroom",
    "Bakuman",
    "One Punch Man",
    "Demon Slayer",
    "Fate",
    "Tobaku Mokushiroku Kaiji",
    "JoJo no Kimyō na Bōken",
    "Bleach",
    "My Hero Academia",
    "Code Geass: Lelouch of the Rebellion",
    "Haikyu!!",
    "Death Note",
    "Fullmetal Alchemist: Brotherhood",
    "Dia no Ace",
    "Attack on Titan",
    "Hunter × Hunter",
    "One Piece; Naruto",
    "Dragonball",
    "Your Name. – Gestern",
    "heute und für immer",
    "A Silent Voice",
    "Gintama",
    "Erased",
    "Weathering with your",
    "Re:Zero – Starting Life in Another World",
    "The Rising of The Shield Hero",
    "That Time i got reincarnated as a slime",
    "Dr Stone",
    "Fire Force",
    "No Game No Life",
    "Toaru No Index/railgun",
    "Noragami",
    "Violet Evergarden",
    "Bunny Girl",
    "Black Clover",
    "Magi: The Labyrinth of Magic",
    "Detektiv Conan",
    "Digimon",
    "Pokemon",
    "The God Of Highschool",
    "Mirai Nikki",
    "Charlotte",
    "Tokyo Ghoul",
    "Tower of God",
    "Puella Magi Madoka Magica",
    "Bungou Stray Dogs",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "From the New World",
    "Kakegurui",
    "Toradora",
    "Golden Time",
    "Golden boy",
    "Parasyte the maxim",
    "Psycho Pass",
    "Kono Subarashii Sekai ni Shukufuku o!",
    "Kaguya-sama: Love is War",
    "Made in Abyss",
    "Berserk",
    "Anohana",
    "Sword Art Online",
    "Yu-Gi-Oh!",
    "Angels of Death",
    "Jujutsu Kaisen",
    "Gotoubun no Hanayome",
    "Oregairu",
    "Boruto",
    "Kuma Kuma Kuma Bear",
    "Rental Girlfriend (Kanojo, Okarishimasu)",
    "Date A Live",
    "The hidden dungeon only i can enter",
    "TONIKAWA: Over the Moon for You",
    "The Pet Girl of Sakurasou",
    "Banana Fish",
    "Deadman Wonderland",
    "Wotakio: Love is Hard for Otaku",
    "Yu Yu Hakusho",
    "Devils' Line",
    "Goblin Slayer",
    "Rage Of Bahamut",
    "Toradora",
    "Beastars",
    "K",
    "Terror in Tokio",
    "So im a spider so what?",
    "SK8",
    "GOD Eater",
    "The Pet Girl of Sakurasou",
    "Angels of Death",
    "Darker Than Black",
    "Is this a Zombie?",
    "Die Walkinder",
    "Black Lagon",
    "Great Pretender",
    "Durarara",
    "BNA",
    "Prinzessin Mononoke",
    "Japan Sinkt 2020",
    "Magic Kaito",
    "Listeners",
    "Cells At Work",
    "The Millionair Detective",
    "2.43: Seiin High School Boys Volleyball Club",
    "22/7",
    "Arte",
    "Azur Lane",
    "Back Arrow",
    "Black Bullet",
    "Darwins Game",
    "Fairy Gone",
    "Fruits Basket",
    "Gleipnir",
    "ID Invaded",
    "IWGP",
    "Log Horizon",
    "Plunderer",
    "Yuri on ice",
    "Toilend-bound Hanako-kun",
    "Chihiros Reise ins Zauberland",
    "Das Wandelnde Schloss",
    "Kikisx Kleiner Lieferservice",
    "Mein Nachbar Totoro",
    "Der Mohnblumenberg",
    "Nausicaä aus dem Tal der Winde",
    "Arrietty- Die wundersame Welt der Borger",
    "Die Chroniken von Erdsee",
    "Das Schloss im Himmel",
    "Ponyo - Das große Abenteuer am Meer",
    "Stimme des Herzens",
    "Wie der Wind sich hebt",
    "Das Königreich der Katzen",
    "Erinnerung an Marnie",
    "Pom Poko",
    "Um ein Schnurrhaar",
    "Flüstern Des Meeres Ocean Waves",
    "Porco Rosso",
    "Die Legende Der Prinzessin Kaguya",
    "Tränen der Erinnerung",
    "Monogatari",
    "Kimi no Suizou wo Tabetai",
    "Your lie in april",
    "Death Parade",
    "Grand Blue",
    "Durarara",
    "Magi: Sinbad no Bouken",
    "angel beats",
    "soul eater",
    "Hataraku Maou-sama",
    "Rokudenashi Majutsu Koushi to Akashic Records",
    "Goblin Slayer",
    "Sakura-sou no Pet na Kanojo",
    "Danmachi",
    "Date a live",
    "Saenai Heroine no Sodatekata",
    "Zankyou no Terror",
    "Oregairu",
    "Vinland Saga",
    "Owari no Seraph",
    "Blue Exorcist",
    "Go-Toubun no Hanayome",
    "Trinity Seven",
    "Jujutsu Kaisen",
    "Kono Yūsha ga Ore Tsuē Kuse ni Shinchō Sugiru",
    "Jibaku Shounen Hanako-kun",
    "Dororo",
    "Hotarobi no Mori e",
    "Great Teacher Onizuka"
)

@KordPreview
object RandomAnime : SlashCommand(
    "randomanime",
    "Pick a random anime from our list"
) {

    override suspend fun handleCommand(interaction: Interaction) {
        interaction.acknowledge(true).followUp {
            embed {
                title = "Der Zufall entscheidet - Welcher Anime?"
                field {
                    val random = animeList.random()
                    name = random
                    value = "Cool, da hat sich der Bot wohl für $random entschieden ${Emojis.slightSmile}! Viel Spaß damit!"
                }
            }
        }
    }

}